version: "3.6"
networks:
  production:
    name: production

services:
  boilerplate-api:
    #entrypoint: ["./wait-for.sh", "mssql:1433", "-t", "120", "--", "dotnet", "Boilerplate.Api.dll"]
    image: boilerplate-api:${TAG}
    container_name: boilerplate-api
    networks: 
        production:
            aliases: 
                - boilerplate-api
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - production
volumes:
  sqlvolume: