version: "3.6"
networks:
  development:
    name: development
services:
  jiban-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: jiban-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yourpassword123
    networks: 
        development:
            aliases: 
                - jiban-db
    volumes:
      - sqlvolume:/var/opt/mssql 
  jiban-api:
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile.dev
      args:
        - SOURCE_SECRETS_PATH=${SOURCE_SECRETS_PATH}
        - DESTINATION_SECRETS_PATH=${DESTINATION_SECRETS_PATH}
        - USER_SECRETS_ID=${USER_SECRETS_ID}
        - ConnectionStrings__SqlServerConnection=${ConnectionStrings__SqlServerConnection}
    image: jiban-api:${TAG}
    container_name: jiban-api
    depends_on:
      - jiban-db
    ports:
      - "44360:44360"
      - "44361:44361"
    networks: 
        development:
            aliases: 
                - jiban-api
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6832:6832/udp"
      - "16687:16687"
    networks:
      - development
volumes:
  sqlvolume: