version: "3.6"
networks:
  Development: 
      name: "Development"
  Production: 
      name: "Production"
services:
  jiban-api-production:
    env_file:
      - .env.production
    environment:
      - Kestrel__Certificates__Default__Path=/src/Certs/ssl.cert
      - Kestrel__Certificates__Default__KeyPath=/src/Certs/ssl.key
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile.production
    image: jiban-api-production:${TAG}
    container_name: jiban-api-production
    ports:
      - "${PORT_HTTP}:${PORT_HTTP}"
      - "${PORT_HTTPS}:${PORT_HTTPS}"
    networks: 
        Production:
            aliases: 
                - jiban-api
  jiban-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: jiban-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yourpassword123
      - TZ=America/Guayaquil
    networks: 
        Production:
            aliases: 
                - jiban-db-development
    volumes:
      - sqlvolume:/var/opt/mssql 
  jiban-api-development:
    env_file:
      - .env.development
    environment:
      - Kestrel__Certificates__Default__Path=/src/Certs/ssl.cert
      - Kestrel__Certificates__Default__KeyPath=/src/Certs/ssl.key
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile.development
    image: jiban-api-development:${TAG}
    container_name: jiban-api-development
    ports:
      - 8080:${PORT_HTTP}
      - 4545:${PORT_HTTPS}
    networks: 
        Development:
            aliases: 
                - jiban-api-development
  jaeger-development:
    container_name: jaeger-development
    image: jaegertracing/all-in-one:latest
    ports:
      - "6832:6832/udp"
      - "16687:16687"
    networks:
      Development:
            aliases:
                - jaeger-development
  jaeger-production:
    container_name: jaeger-Production
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"   
    networks: 
        Production:
            aliases: 
                - jaeger-production
volumes:
  sqlvolume: